# kind: pipeline
# type: docker
# name: greeting

# steps:
# - name: en
#   image: alpine
#   commands:
#   - echo hello
#   - echo world
#---
kind: pipeline
type: exec
name: default

platform:
  os: darwin
  arch: amd64

# setup:
#   image: docker:git
#   commands:
#   - git clone https://github.com/kapeterson/GoApi.git
steps:
- name: greeting
  commands:
  - echo hello world
  - echo bro wassup son
  - docker run hello-world
  - pwd
  - git clone https://github.com/kapeterson/cs.git
  - docker run --mount type=bind,source="$(pwd)"/body.json,target=/tmp hello-world
  - docker run --rm --mount type=bind,source="$(pwd)"/cs/python/count.py,target=/tmp/hello.py kp/python-test python count.py
