# kind: pipeline
# type: docker
# name: greeting

# steps:
# - name: en
#   image: alpine
#   commands:
#   - echo hello
#   - echo world
#---
kind: pipeline
type: exec
name: default

platform:
  os: darwin
  arch: amd64

steps:
- name: greeting
  commands:
  - echo hello world
  - echo bro wassup son
  - docker run hello-world
  - pwd
  - docker run --mount $type=bind,source="$(pwd)"/body.json,target=/tmp
